name: Notify assignees when their card moves between columns

on:
  project_card:
      types: ["moved"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: bidwrangler/project-card-moved-notification-action@master
          with:
            assigneeFilter: chris-bidwrangler
                  

    
